dist: bionic
sudo: false

language: node_js
node_js:
  - '13.3.0'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./frontend/node_modules
    - ./backend/node_modules

install:
  - cd frontend
  - npm install
  - cd ../backend
  - npm install

before_script:
  - npm install -g gulp-cli

script:
  - cd ../frontend
  - ng build --prod
  - cd ../backend
  - gulp
  #- npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox