dist: bionic
sudo: false

language: node_js
node_js:
  - '13.3.0'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./frontend/node_modules
    - ./backend/node_modules

before_script: cd frontend

install:
  - cd frontend
  - npm install
  - cd ../backend
  - npm install

script:
  - cd frontend
  - ng build --prod
  #- npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox